version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
